apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: braintipster
  namespace: '443956544427'
  selfLink: /apis/serving.knative.dev/v1/namespaces/443956544427/services/braintipster
  uid: bef540c3-7948-4fe4-be97-22883942bae5
  resourceVersion: AAY3oWdPMKA
  generation: 7
  creationTimestamp: '2025-05-31T14:56:03.388003Z'
  labels:
    managed-by: google-ai-studio
    cloud.googleapis.com/location: us-west1
  annotations:
    serving.knative.dev/creator: notaro.enrico@gmail.com
    serving.knative.dev/lastModifier: notaro.enrico@gmail.com
    run.googleapis.com/ingress: all
    generativelanguage.googleapis.com/type: applet
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: 8ef8a381-70d8-43ee-9953-7633cdeb6d9f
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://braintipster-443956544427.us-west1.run.app","https://braintipster-y5st4ppywa-uw.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 2c222a72-9019-45c9-bd18-4db37ba3b925
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/base-images: '{"applet-proxy-1":"us-central1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
        run.googleapis.com/startup-cpu-boost: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 443956544427-compute@developer.gserviceaccount.com
      containers:
      - name: applet-proxy-1
        image: us-docker.pkg.dev/cloudrun/container/aistudio/applet-proxy
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SPORTS_API_KEY
          value: 4051f2a9968715ee2d76dbbadb1ec3a7
        - name: OPENROUTER_API_KEY
          value: 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
        - name: N8N_RESULTS_WEBHOOK_URL
          value: https://chamatar90.app.n8n.cloud/webhook-test/81f64a58-3e2b-40e2-aba1-657a75fad504
        - name: FRONTEND_API_KEY
          value: e20AL7XEDZVXQ3n3ly2v7SSE5YBl5fpi3GkzQM858oUHTM8bdMM5v3yvUEKlXYUkyGRVhExQr7CnCJDO6PWZhoNvC1iJCnGhoxBlpxeLUYdmnyIDHEEa5unTbZhpVsg8
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - name: applet
          mountPath: /app/dist
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      volumes:
      - name: applet
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: ai-studio-bucket-443956544427-us-west1
            mountOptions: only-dir=services/braintipster/version-2/compiled
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 7
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2025-06-15T19:37:02.769312Z'
  - type: BaseImageValidated
    status: 'True'
    severity: Info
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2025-06-15T19:37:02.223969Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2025-06-15T19:37:02.732113Z'
  latestReadyRevisionName: braintipster-00006-jg6
  latestCreatedRevisionName: braintipster-00006-jg6
  traffic:
  - revisionName: braintipster-00006-jg6
    percent: 100
    latestRevision: true
  url: https://braintipster-y5st4ppywa-uw.a.run.app
  address:
    url: https://braintipster-y5st4ppywa-uw.a.run.app
